external:
    server:
        port: 8081
        uri: http://localhost

iban:
    bankcode: 11111111
    checkdigits: 91
    countrycode: DE

server:
    port: ${SERVER_PORT}
    uri: ${SERVER_URI}

spring:
    application:
        name: bank
    jpa:
        hibernate:
            ddl-auto: create

springdoc:
    show-login-endpoint: true

security:
    jwt:
        secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        jwt-expiration-ms: 8640000
